Servers: 5
Cpu: "2"
Memory: "4Gi"
Heap: "2G"
Storage: "250Gi"
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
Image: "gcr.io/google_containers/kubernetes-zookeeper:1.0-3.5.5"
ImagePullPolicy: "Always"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity: "hard"
LogLevel: "INFO"
MaxSessionTimeout: 40000
MinSessionTimeout: 4000
UpdateStrategy: RollingUpdate
MaxUnavailable: 1